---
# tasks file for asa_noturna
- name: Roles for deploy
  hosts: all
  vars: 
    - texto: "Glória a Deuxxxxxxxx"
  tasks:
    - include: prereqDebian.yml
    - include: prereqRedhat.yml
    - include: install_nginx.yml
    - include: deploy.yml

