- name: Stop HTTPD - Like Red Hat
  service: 
    name: httpd
    state: stopped
  ignore_errors: True
  when: ansible_os_family == "RedHat"

- name: Remove HTTPD - Like Red Hat
  yum:
    name: httpd
    state: absent
  when: ansible_os_family == "RedHat"
    
